### PR TITLE
Make all loading be properly async

### LINKED ISSUE #456: The "Atom property coloring" example is broken
Currently unclear about which update leads to this error. See https://chemiscope.org/docs/examples/4-colors.html#atom-property-coloring
Image

### PR DESCRIPTION
**Pull request by ceriottm**
Fixes #456  and probably is saner.

### CODE REVIEW

**Comment by ceriottm** [comment]
> It worked. Can we try to capture these kinds of errors in the CI? It seems like we can only capture the errors at the python side but have no ideas about if the typescript works and how it would finally look like in the jupyter widget

I think we tried to have something at some point but it's very hard to test what the browser (or jupyter) renders

File: src/structure/grid.ts [hunk 1]
```diff
@@ -131,7 +131,7 @@ export class ViewersGrid {
     /// List of structures in the dataset
     private _structures: Structure[] | UserStructure[];
     /// List of per-atom properties in the dataset
-    private _properties: Record<string, number[]>;
+    public _properties: Record<string, number[]>;
```
Comment (Luthaf) [inline src/structure/grid.ts]:
```suggestion
    private _properties: Record<string, number[]>;
```

Comment (ceriottm) [reply src/structure/grid.ts]: well spotted!
